[tool.poetry]
name = "2024-p2"
version = "0.1.0"
description = ""
authors = ["Brook Queree <github.com/bhq12>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.2"
flake8 = "^7.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
