CREATE TABLE IF NOT EXISTS todos (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title STRING(80) NOT NULL,
	description STRING(120) NULL,
	completed BOOLEAN NOT NULL DEFAULT FALSE,
	deadline_at DATETIME NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
